<a href="https://colab.research.google.com/github/itsparser/colab/blob/live-session/Numpy_Noob2Pro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 align='center'>Numpy</h1>

<h2>Table of contents</h2>
<ol>
    <li><a href='#5'>What is NumPy?</a></li>
    <li><a href='#6'>Why NumPy?</a></li>
    <li><a href='#1'>Numpy Array</a></li>
    <li><a href='#2'>N-Dimensional Array</a></li>
    <li><a href='#7'>Broadcasting</a></li>
    <li><a href='#3'>Memory mapped files</a></li>
    <li><a href='#4'>References</a></li>
</ol>

<a id='5'></a>
## What is NumPy?

![1_mc5YIn7jvo5uwuqBOUDw7Q.jpeg](attachment:1_mc5YIn7jvo5uwuqBOUDw7Q.jpeg)

* NumPy is the fundamental package for scientific computing in Python. 
* It is a Python library that provides 
    * a multidimensional array object, 
    * various derived objects (such as masked arrays and matrices), and 
    * an assortment of routines for fast operations on arrays, 
    * including mathematical, logical, shape manipulation, 
    * sorting, selecting, 
    * I/O, discrete Fourier transforms, 
    * basic linear algebra, basic statistical operations, random simulation and much more.

![main-qimg-f6059241bfb8a45594b9c73b151a8b61.png](attachment:main-qimg-f6059241bfb8a45594b9c73b151a8b61.png)

![main-qimg-e93f0acb91c7b3ef0d92894a989fb161.png](attachment:main-qimg-e93f0acb91c7b3ef0d92894a989fb161.png)

<a id='6'></a>
## Why Numpy?

* A common beginner question is what is the real difference here. The answer is performance. Numpy data structures perform better in:
    * **Size** - Numpy data structures take up less space
    * **Performance** - they have a need for speed and are faster than lists
    * **Functionality** - SciPy and NumPy have optimized functions such as linear algebra operations built in.

**Memory**

* The main benefits of using NumPy arrays should be smaller memory consumption and better runtime behavior. 

* For Python Lists -  We can conclude from this that for every new element, we need another eight bytes for the reference to the new object. The new integer object itself consumes 28 bytes. The size of a list "lst" without the size of the elements can be calculated with:

    * 64 + 8 * len(lst) + len(lst) * 28

![list_structure.png](attachment:list_structure.png)

* NumPy takes up less space. This means that an arbitrary integer array of length "n" in numpy needs

    * 96 + n * 8 Bytes

* whereas a list of integer

![array_structure.png](attachment:array_structure.png)

**Speed**

* This shows some performance numbers of operations between Python and Numpy.

In [0]:
import time
import numpy as np

size_of_vec = 1000

def pure_python_version():
  """Adding two arrays using pure python"""
  t1 = time.time()
  X = range(size_of_vec)
  Y = range(size_of_vec)
  Z = [X[i] + Y[i] for i in range(len(X)) ]
  return time.time() - t1

def numpy_version():
  """Adding two arrays using numpy"""  
  t1 = time.time()
  X = np.arange(size_of_vec)
  Y = np.arange(size_of_vec)
  Z = X + Y
  return time.time() - t1


t1 = pure_python_version()
t2 = numpy_version()
print("Pure python: " + str(t1))
print("Numpy: " + str(t2))
print("\nNumpy is in this example " + str(t1/t2) + " faster!")

Pure python: 0.0005288124084472656
Numpy: 5.14984130859375e-05

Numpy is in this example 10.268518518518519 faster!


<a id='1'></a>
## Numpy Array

* The ndarray (NumPy Array) is a multidimensional array used to store values of same datatype.
* These arrays are indexed just like Sequences, starts with zero.

![elsp_0105.png](attachment:elsp_0105.png)

* NumPy Arrays come in two forms; Vectors and Matrices. 
    * Vectors are strictly one-dimensional(1-d) arrays, 
    * while Matrices are multidimensional. In some cases, Matrices can still have only one row or one column.

**Let’s start by importing NumPy in your Jupyter notebook.**

In [0]:
import numpy as np

**Creating numpy arrays from python lists**

In [0]:
my_list = [1,2,3,4,5]

**We can simply create a NumPy array called my_numpy_list and display the result:**

In [0]:
my_numpy_list = np.array(my_list)
my_numpy_list  #This line show the result of the array generated

array([1, 2, 3, 4, 5])

![Screenshot%20from%202018-05-10%2002-04-19.png](attachment:Screenshot%20from%202018-05-10%2002-04-19.png)

**Creating NumPy array using arange() built-in function.**

* Similar to the python built-in range() function, we will create a NumPy array using arange().

In [0]:
my_list = np.arange(10)
#OR
my_list = np.arange(0,10)
my_list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

![Screenshot%20from%202018-05-10%2002-05-15.png](attachment:Screenshot%20from%202018-05-10%2002-05-15.png)

* This generates 10 digits of values from index 0 to 10.
* It is important to note that the arange() function can also take 3 arguments. 
* The third argument signifies the step size of the operation. 
* For example, to get all even numbers from 0 to 10, simply add a step size of 2 like below.

In [0]:
my_list = np.arange(0,11,2)
my_list

array([ 0,  2,  4,  6,  8, 10])

**We can also generate a one-dimensional array of seven zeros.**

In [0]:
my_zeros = np.zeros(7)
my_zeros

array([0., 0., 0., 0., 0., 0., 0.])

![Screenshot%20from%202018-05-10%2012-20-16.png](attachment:Screenshot%20from%202018-05-10%2012-20-16.png)

<a id='2'></a>
## N-Dimensional Array

![main-qimg-cc51a4de89837eca971f0202e7572d88.png](attachment:main-qimg-cc51a4de89837eca971f0202e7572d88.png)

**To get a 2-dimensional array, we have to cast a list of list as shown below.**

In [0]:
second_list = [[1,2,3], [5,4,1], [3,6,7]]
new_2d_arr = np.array(second_list)
new_2d_arr  #This line show the result of the array generated

array([[1, 2, 3],
       [5, 4, 1],
       [3, 6, 7]])

In [0]:
type(new_2d_arr)

numpy.ndarray

In [0]:
new_2d_arr.shape

(3, 3)

**Slicing Arrays, like other Python sequences can also be sliced:**

![numpy_indexing.png](attachment:numpy_indexing.png)

In [0]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**[start:end:step]**

**All three slice components are not required: by default, start is 0, end is the last and step is 1**

In [0]:
a[2:9:3]

array([2, 5, 8])

**Numerical operations on arrays**

**With scalars:**

In [0]:
a = np.array([1, 2, 3, 4])
a + 1

array([2, 3, 4, 5])

**All arithmetic operates elementwise:**

In [0]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
a + b

array([2, 4, 6, 8])

**Array multiplication is not matrix multiplication:**

In [0]:
c = np.ones((3, 3))
c * c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**Matrix Multiplication**

In [0]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
a.dot(b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

![matrix-multiplication.jpg](attachment:matrix-multiplication.jpg)

![Screenshot%20from%202018-05-10%2012-21-26.png](attachment:Screenshot%20from%202018-05-10%2012-21-26.png)

**Example: data statistics**

* Data in populations.txt describes the populations of hares and lynxes (and carrots) in northern Canada during 20 years.

* We can first plot the data:

In [0]:
data = np.loadtxt('data/populations.txt')
year, hares, lynxes, carrots = data.T
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [0]:
np.argmax(data,axis=0)

TypeError: argmax() missing 1 required positional argument: 'a'

![Screenshot%20from%202018-05-10%2012-22-36.png](attachment:Screenshot%20from%202018-05-10%2012-22-36.png)

**The mean populations over time:**

![Picture5.png](attachment:Picture5.png)

In [0]:
populations = data[:, 1:]
populations.mean(axis=0)

array([34080.95238095, 20166.66666667, 42400.        ])

In [0]:
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [0]:
np.argmax(populations, axis=0)

array([3, 4, 0])

In [0]:
np.argmax(populations, axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

![Screenshot%20from%202018-05-10%2012-23-42.png](attachment:Screenshot%20from%202018-05-10%2012-23-42.png)

**The Sample standard deviation**

![main-qimg-305ff0d5aaf85e1c467e3c10d6e603c8.gif](attachment:main-qimg-305ff0d5aaf85e1c467e3c10d6e603c8.gif)

In [0]:
populations.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

![Screenshot%20from%202018-05-10%2012-24-23.png](attachment:Screenshot%20from%202018-05-10%2012-24-23.png)

**Which species has the highest population each year?**

In [0]:
np.argmax(populations, axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

![Screenshot%20from%202018-05-10%2012-25-10.png](attachment:Screenshot%20from%202018-05-10%2012-25-10.png)

<a id='7'></a>
## Broadcasting

* Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations.
* Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

* For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [0]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


![Screenshot%20from%202018-05-10%2011-59-14.png](attachment:Screenshot%20from%202018-05-10%2011-59-14.png)

* This works; however when the matrix x is very large, computing an explicit loop in Python could be slow. 
* Note that adding the vector v to each row of the matrix x is equivalent to forming a matrix vv by stacking multiple copies of v vertically, then performing elementwise summation of x and vv.
* We could implement this approach like this:

In [0]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

# Stack 4 copies of v on top of each other
vv = np.tile(v, (4, 1))   
print(vv)                 

# Add x and vv elementwise
y = x + vv  
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


![Screenshot%20from%202018-05-10%2012-07-12.png](attachment:Screenshot%20from%202018-05-10%2012-07-12.png)

* Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. 
* Consider this version, using broadcasting:

In [0]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

# Add v to each row of x using broadcasting
y = x + v  
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


* The line y = x + v works even though x has shape (4, 3) and v has shape (3,) due to broadcasting; 
* this line works as if v actually had shape (4, 3), where each row was a copy of v, and the sum was performed elementwise.

**Broadcasting two arrays together follows these rules:**

* If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
* The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
* The arrays can be broadcast together if they are compatible in all dimensions.
* After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
* In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

* Functions that support broadcasting are known as universal functions.

**Here are some applications of broadcasting:**

In [0]:
import numpy as np

# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [0]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

[[2 4 6]
 [5 7 9]]


In [0]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [0]:
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [0]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]


* Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

![Screenshot%20from%202018-05-10%2012-27-49.png](attachment:Screenshot%20from%202018-05-10%2012-27-49.png)

<a id='3'></a>
## Memory Mapped Files

* A memory-mapped file contains the contents of a file in virtual memory.
* This mapping between a file and memory space enables an application, including multiple processes, to modify the file by reading and writing directly to the memory

![1.jpg](attachment:1.jpg)

**There are two types of memory-mapped files:**

* Persisted memory-mapped files

    * Persisted files are memory-mapped files that are associated with a source file on a disk.
    * When the last process has finished working with the file, the data is saved to the source file on the disk. 
    * These memory-mapped files are suitable for working with extremely large source files.

* Non-persisted memory-mapped files

    * Non-persisted files are memory-mapped files that are not associated with a file on a disk.
    * When the last process has finished working with the file, the data is lost and the file is reclaimed by garbage collection. 
    * These files are suitable for creating shared memory for inter-process communications (IPC).

![Screenshot%20from%202018-05-10%2002-57-09.png](attachment:Screenshot%20from%202018-05-10%2002-57-09.png)

* The memmap object can be used anywhere an ndarray is accepted. Given a memmap fp, isinstance(fp, numpy.ndarray) returns True.

* Memory-mapped files cannot be larger than 2GB on 32-bit systems.



**Examples**
* This example uses a temporary file so that doctest doesn’t write files to your directory. You would use a ‘normal’ filename.

In [0]:
from tempfile import mkdtemp
import os.path as path
filename = path.join(mkdtemp(), 'newfile.dat')

**Create a memmap with dtype and shape that matches our data:**

In [0]:
fp = np.memmap(filename, dtype='float32', mode='w+', shape=(3,4))
fp

memmap([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=float32)

**Write data to memmap array:**

In [0]:
data = np.arange(12, dtype='float32')
data.resize((3,4))

![Screenshot%20from%202018-05-10%2012-28-48.png](attachment:Screenshot%20from%202018-05-10%2012-28-48.png)

In [0]:
fp[:] = data[:]
fp

memmap([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=float32)

**Deletion flushes memory changes to disk before removing the object:**

In [0]:
del fp

**Load the memmap and verify data was stored:**

In [0]:
newfp = np.memmap(filename, dtype='float32', mode='r', shape=(3,4))
newfp

memmap([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=float32)

**Read-only memmap:**

In [0]:
fpr = np.memmap(filename, dtype='float32', mode='r', shape=(3,4))
fpr.flags.writeable

False

**Copy-on-write memmap:**

In [0]:
fpc = np.memmap(filename, dtype='float32', mode='c', shape=(3,4))
fpc.flags.writeable

True

**It’s possible to assign to copy-on-write array, but values are only written into the memory copy of the array, and not written to disk:**

In [0]:
fpc

memmap([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=float32)

In [0]:
fpc[0,:] = 0

In [0]:
fpc

memmap([[ 0.,  0.,  0.,  0.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=float32)

**File on disk is unchanged:**

In [0]:
fpr

memmap([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=float32)

<a id='4'></a>
## References

* https://webcourses.ucf.edu/courses/1249560/pages/python-lists-vs-numpy-arrays-what-is-the-difference
* https://towardsdatascience.com/lets-talk-about-numpy-for-datascience-beginners-b8088722309f
* https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.memmap.html
* http://www.scipy-lectures.org/intro/numpy/numpy.html#basic-visualization
* http://cs231n.github.io/python-numpy-tutorial/